import 'react-toastify/dist/ReactToastify.css';
import 'react-date-range/dist/styles.css';
import 'react-date-range/dist/theme/default.css';
import "./globals.scss";

import {Roboto} from "next/font/google";
import QueryProvider from "@/components/tanstack/QueryProvider";
import {AuthProvider} from "@/provider/AuthProvider";
import {GlobalProvider} from "@/provider/GlobalProvider";
import {ToastContainer} from 'react-toastify';

const roboto = Roboto({
    subsets: ["latin"], // Chọn subset phù hợp, ví dụ: "latin", "cyrillic", v.v.
    weight: ["100", "300", "400", "500", "700", "900"], // Chọn các trọng số cần sử dụng
    variable: "--font-roboto", // Tên biến CSS để sử dụng trong className
});

export const metadata = {
    title: "USTH - Document search",
    description: "USTH - Document search by Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${roboto.variable} antialiased`}>
        <QueryProvider>
            <AuthProvider>
                <GlobalProvider>
                    <ToastContainer position="bottom-left"/>
                    {children}
                </GlobalProvider>
            </AuthProvider>
        </QueryProvider>
        </body>
        </html>
    );
}
